### ISSUE TITLE
Possible logic error in chunk?

### ISSUE THREAD

**Issue by jonsterling** [davdar/final-pretty-printer#4]
We were debugging an issue with the [SML version of `final-pretty-printer`](https://github.com/RedPRL/sml-final-pretty-printer) and came across what may be a logic error in the `chunk` algorithm.

In short, there is the following code which determines whether to raise a fault:

```
    w <- measureCurLine
    n <- askNesting
    when (n + w > wmax) empty
    when (w     > rmax) empty
```

Observe that when nesting is enacted (through `newline`), spaces of the appropriate width are added to the current line (using `chunk`). So, in this part of `chunk`, it looks like this whitespace is counted twice: first in the size of the current line `w`, and second in the nesting `n`. Concretely, this results in code being too aggressively broken, when there is sufficient width for it to remain flat.

We believe that this code can be changed to the following:

```
    w <- measureCurLine
    n <- askNesting
    when (w > wmax) empty
    when (w - n > rmax) empty
```

We have tried this change out in our SML port, and it appears to give the correct result. What do you think?

--- @jonsterling and @cangiuli

**Comment by davdar** [comment]
Hi Jon,

Sorry for the late response. Yes this is a bug, and your fix looks right.

**Comment by jonsterling** [comment]
@davdar No worries, @cangiuli and I are relieved you agree!

**Comment by jonsterling** [comment]
I opened a pull request so that you can close this ticket :smile:
